version: '3'

volumes:
  laratest_postgres_data: {}
  laratest_postgres_data_backups: {}
  lataratest_redis: {}

services:
  postgres: &postgres
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: laratest_postgres
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - laratest_postgres_data:/var/lib/postgresql/data
      - laratest_postgres_data_backups:/backups
    env_file:
      - ./.env
    ports:
      - "5433:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
